"""Create Test, User, Organisation, Member, and Role tables

Revision ID: 835190cf4b27
Revises: e0252544f31c
Create Date: 2024-09-14 18:19:22.498618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835190cf4b27'
down_revision: Union[str, None] = 'e0252544f31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
