"""Create Test, User, Organisation, Member, and Role tables

Revision ID: c18e313752f8
Revises: 835190cf4b27
Create Date: 2024-09-14 19:47:27.343795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18e313752f8'
down_revision: Union[str, None] = '835190cf4b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
